('admin1', 'id', 'integer')
('admin2', 'id', 'integer')
('sample', 'id', 'integer')
('sample', 'sal_id', 'integer')
('admin3', 'id', 'integer')
('salaries', 'sal_id', 'integer')
('salaries', 'salary', 'double precision')
('admin1', 'name', 'character varying')
('sample', 'dept', 'character varying')
('admin2', 'name', 'character varying')
('admin3', 'name', 'character varying')
('sample', 'name', 'character varying')
('sample', 'designation', 'character varying')
